### ISSUE TITLE
No module tensorrt found

### ISSUE THREAD

**Issue by shoebNTU** [prratadiya/tensorrt-installation-colab#1]
Hello, thanks a lot for sharing this repo. I am able to download tensorrt correctly following your steps. However, when i try to import tensorrt i get module not found. Could you please help me debug it? Thanks.

**Comment by pratikratadiya** [comment]
Hello Shoaib!
Are you in the same session? A restart in Colab would mean issues with the finding the module.

You may also find some help here: https://stackoverflow.com/questions/55557912/importerror-no-module-named-tensorrt

Thank you.

**Comment by forever208** [comment]
> Hello Shoaib!
> Are you in the same session? A restart in Colab would mean issues with the finding the module.
> 
> You may also find some help here: https://stackoverflow.com/questions/55557912/importerror-no-module-named-tensorrt
> 
> Thank you.

I've got the same problem, any help would be greatly appreaciated

**Comment by forever208** [comment]
@shoebNTU @prratadiya I solved this problem by restart the runtime

**Comment by codebugged** [comment]
Hi @forever208 
Did you only restart the runtime ?
Or you also installed any library ?
